### ISSUE TITLE
Upper case at jpg files extensions returns an error

### ISSUE THREAD

**Issue by bmyagkov** [PhotoFlare/photoflare#192] opened 2019-03-06 05:34 UTC
**Description**
Same file with extension turned from .jpg to .JPG makes impossible to view the image

**Steps to reproduce**
1.	Manually change any random .jpg file extension to upper case format
2.	Open edited file 
3.	Click SAVE button from the popup warning menu 

**Actual result**
File appears as grey background which is also have right file path at status bar but with inappropriate backslash there 

**Expected Result**
There should be no difference what case the file extension has. The program should ignore this.

**Environment**
Windows 10 LTSC x64
Windows 7 Professional x64
PhotoFlare 1.5.7
![1](https://user-images.githubusercontent.com/47425413/53858227-f45c0500-400b-11e9-9c71-0b83cae9f243.gif)

**Comment by DylanC** [comment] 2019-03-06 10:19
@bmyagkov - I tried to get around this issue with the rename feature. The problem is with the libraries the program is built on. Not with the program itself.

Maybe in this case it should not rename but fix the case of the letters.

**Comment by DylanC** [comment] 2019-03-09 09:58
@bmyagkov - Pushed fix for this. Thanks.

**Closed by DylanC** 2019-03-09 09:58 UTC
Labels: bug
