### ISSUE TITLE
Step of Clone Stamp does not change in unfixed mode

### ISSUE THREAD

**Issue by PolliRedHead** [PhotoFlare/photoflare#178] opened 2019-01-11 05:26 UTC
Summary: Step of Clone Stamp does not change in unfixed mode.
Component: Step of Clone Stamp.
Version: 1.5.6.1.
Severity: Major.
Platform: Windows 10 x64.
Steps to reproduce:
1. Start program.
2. Click "open" button.
3. Open an any image.
4. Select Clone Stamp.
5. Change Step.
Result: Step of Clone Stamp does not change.
Expected Result: Step of Clone Stamp changed.

Comment: You can change Step of Clone Stamp if you select a Fixed mode.

**Comment by DylanC** [comment] 2019-01-14 11:03
@PolliRedHead - You must enable fixed now to change the step control. Step control is disabled unless you click the fixed checkbox. This is intended behavior but maybe this should be covered in the documentation.

**Comment by DylanC** [comment] 2019-01-21 15:30
Updated in the documentation thanks.
https://photoflare.io/documentation/the-toolpalette/

**Closed by DylanC** 2019-01-21 15:30 UTC
Labels: docs
